from . import hr
from . import hr_budget
from . import hr_contract_model
from . import Hr_dasc
from . import hr_employee
from . import Hr_FDFP
from . import hr_its
from . import hr_payroll_analyse
from . import hr_payroll_ci
from . import HrSalaryRule
from . import res_company
from . import res_config_settings
from . import hr_cnps_settings
from . import hr_cnps_monthly
from . import hr_cgrae_export
from . import hr_cmu
from . import payroll_crrae
from . import hr_payroll_disa
from . import hr_EmployeePayrollDispatch
from . import hrFdfpConfig
from . import hrFDFP
from . import account_move_template
from . import hr_payroll_inherit
from . import hr_salary_employee_variation
from . import heures_supplementaires
from . import payroll_balance_any_account
from . import hr_301

