from . import hr_holidays
from . import hr_employee
from . import res_company
from . import res_config_setting
from . import hr_holiday_previsional
from . import hr_holiday_stock
from . import hr_holidays_planning
from . import hr_holidays_provision
from . import hr_payroll_holidays_provision
from . import hr_holidays_recovery
from . import hr_salary_rule
from . import hr_holiday_payroll
