{
    "name": "HR PAYROLL",
    "version": "1.0",
    "author": "VEONE",
    'category': 'Payroll',
    "website": "http://www.veone.net",
    "depends": ["hr_payroll", 'hr_employee_custom', 'hr_contract_custom', 'hr_holidays', 'report_xlsx', 'web', 'hr',
                "hr_attendance", "hr_work_entry_contract"
                ],
    "description": """
    """,
    "init_xml": [],
    "demo_xml": [],
    "update_xml": [],
    "data": [
        'security/security.xml',
        "security/ir.model.access.csv",
        'data/report_data.xml',
        "views/hr_view.xml",
        'views/hr_rapport_menu.xml',
        "views/hr_account_move_salary_template_view.xml",
        'data/hr_overtimes_data.xml',
        'views/res_config_settings_views.xml',
        'wizard/HrPayrollView.xml',
        'report/templates/layout_payslip_view.xml',
        'wizard/payroll_by_post_view.xml',
        'wizard/cumulative_payroll_by_post_view.xml',
        'wizard/contributions_by_organization_view.xml',
        'wizard/agent_payments_view.xml',
        'wizard/salary_mass_view.xml',
        'wizard/import_advantages_301_view.xml',
        'wizard/workforce_by_detailed_position_view.xml',
        'views/hr_salary_rule_view.xml',
        'views/report_payroll.xml',
        'views/hr_payslip_view.xml',
        'views/hr_analyse_view.xml',
        'views/hr_budget_view.xml',
        'views/hr_301_view.xml',
        "views/hr_asset_backend.xml",
        'data/report_paperformat_data.xml',
        'report/report_positionnal_charge.xml',
        'report/report_statement_payroll_ci_raport.xml',
        'report/report_payroll_by_period.xml',
        'report/hr_301_list_report.xml',
        'report/hr_301_list_report_recap.xml',
        "report/report_transfer_order.xml",
        "report/report_summary_slips.xml",
        "report/report_transfer_mail.xml",
        "wizard/hrTransferOrderView.xml",
        'report/report_view.xml',
        'report/report_payslip_without_header.xml',
        "wizard/import_payslip_inputs_view.xml",
        "wizard/hr_compute_inverse_view.xml",
        "wizard/import_salary_element_view.xml",
        'data/hr_payroll_structure_data.xml',
        'data/email_data.xml',
        'data/ir_cron_data.xml',
        'data/hr_salary_rule_data.xml',
        'data/hr_salary_rule_category_data.xml',
        'data/hr_cnps_settings_data.xml',
        "wizard/hr_payroll_inverse_view.xml",
        "views/hr_payroll_ci.xml",
        'report/templates/layout_view.xml',
        "views/res_company_view.xml",
        "report/report_payslip.xml",
        "views/hr_payroll_balance_any_account_view.xml",
        'views/hr_contract_model_view.xml',
        "views/hr_employee_inherit_view.xml",
        "views/hr_cnps_settings_view.xml",
        "views/hr_cnps_monthly_view.xml",
        "report/report_cnps_monthly.xml",
        "report/cnps_mensuel_pdf.xml",
        "views/hr_convention_view.xml",
        "views/hr_cgrae_export_wizard_view.xml",
        "views/report_cgrae_list.xml",
        "report/report_hr_cgrae.xml",
        "views/hr_cmu_wizard_view.xml",
        "views/hr_payroll_crrae_view.xml",
        "wizard/import_advantages_view.xml",
        "report/report_hr_disa_pdf.xml",
        "report/cnps_yearly_report_pdf.xml",
        "views/hr_payroll_disa_view.xml",
        'report/report_hr_its_complement.xml',
        'views/hr_its_view.xml',
        "views/hr_fdfp_setting_view.xml",
        'views/hr_fdfp_view.xml',
        "report/report_c_tax_hr_fdfp.xml",
        "views/hr_salary_employee_variation.xml",
        "report/report_hr_salary_missing_to_previous_pay.xml",
        "report/report_hr_salary_management_of_pay_differentials.xml",
        "wizard/hr_salary_variation.xml",
        "views/hr_heures_supplementaires_view.xml",
        "wizard/hr_compute_inverse_view.xml",
        "wizard/import_salary_element_view.xml",
        "wizard/hr_departure_inherit.xml",
    ],
    "installable": True

}
