{
    "name": "HR HOLIDAY CUSTOM",
    "version": "1.0",
    "author": "VEONE",
    'category': 'Holiday',
    "website": "http://www.veone.net",
    "depends": ["base", "hr_holidays", "hr_employee_custom", "hr_payroll_custom"],
    "description": """
    """,
    "init_xml": [],
    "demo_xml": [],
    "update_xml": [],
    "data": [
        'data/ir_module_category_data.xml',
        'security/groups.xml',
        'security/security.xml',
        "security/ir.model.access.csv",
        'data/salary_rule.xml',
        'data/salary_rule_functionnaire.xml',
        'data/holidays_email_departement_template.xml',
        'data/template_email_alert_late_return_leave.xml',
        'data/cron_create_holiday_provision.xml',
        'data/cron_late_return_leave_alert.xml',
        'data/cron_holiday_email_year.xml',
        'data/hr_leave_view_inherit.xml',
        'data/cron_save_stock_holiday.xml',
        'data/cron_planning_holiday_template.xml',
        'data/holidays_email_real_planning_template.xml',
        'data/cron_view.xml',
        'views/hr_holiday_menu.xml',
        'views/hr_holiday_payroll.xml',
        'wizards/hr_holidays_refuse_wizard_view.xml',
        'views/hr_holidays_view.xml',
        'views/hr_holidays_planning_view.xml',
        'views/hr_holidays_provisions_view.xml',
        'views/hr_holidays_recovery_view.xml',
        'views/hr_employee_view.xml',
        'views/hr_historique_planning.xml',
        'views/res_config_settings_view.xml',
        'views/hr_holidays_previsional.xml',
        'views/hr_salary_rule_view.xml',
        'wizards/hr_holiday_department_wizard.xml',
        'wizards/hr_planning_holiday_monthly_wizard.xml',
        'wizards/hr_planning_holiday_yearly_wizard.xml',
        'report/report_view.xml',
        'report/templates/layouts.xml',
        'report/report_agent_on_leave.xml',
        'report/report_hr_planning_holiday_yearly_pdf.xml',
        'report/report_hr_holidays_department_pdf.xml',
        'report/report_synthetic_holiday.xml',
        'report/report_hr_holidays_recovery.xml',
    ],
    "installable": True

}
